spring:
  application:
    name: apollo-portal
  profiles:
    active: github,auth

server:
  port: 21010
  compression:
    enabled: true
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


